/**
 * Centralized backend error code registry.
 *
 * Codes use `<GROUP>.<KEY>` notation. The frontend's `apiError()` splits on
 * the dot and looks up `errors.<group>.<KEY>` in the i18n catalog, so adding
 * a new code here MUST be paired with a matching entry under the same path
 * in `src/i18n/locales/<locale>/errors.json` (English first, then synced to
 * the other locales by the `sync_keys` script).
 *
 * Conventions:
 *   - GROUP is the domain ("AUTH", "USER", "APPLICANT", …) — uppercase, no
 *     underscores. Reuse before inventing.
 *   - KEY is the verb/state ("NOT_FOUND", "ALREADY_EXISTS", "INVALID") —
 *     uppercase with `_` separators.
 *   - Prefer reuse (`USER.NOT_FOUND`, not `USER_NOT_EXISTS`) so locale
 *     catalogs stay flat and translators have fewer near-duplicates to
 *     handle.
 *
 * The backend never sends free-form English to the frontend for new
 * exceptions — it sends `{ code, message, params }` and lets the client
 * pick the locale.
 */
export const ErrorCodes = {
  // ── Generic envelope (also emitted by the filter as a default fallback)
  GENERIC: {
    BAD_REQUEST:       'GENERIC.BAD_REQUEST',
    UNAUTHORIZED:      'GENERIC.UNAUTHORIZED',
    FORBIDDEN:         'GENERIC.FORBIDDEN',
    NOT_FOUND:         'GENERIC.NOT_FOUND',
    CONFLICT:          'GENERIC.CONFLICT',
    UNIQUE_VIOLATION:  'GENERIC.UNIQUE_VIOLATION',
    UNPROCESSABLE:     'GENERIC.UNPROCESSABLE',
    RATE_LIMITED:      'GENERIC.RATE_LIMITED',
    UNEXPECTED:        'GENERIC.UNEXPECTED',
  },

  // ── Authentication & session
  AUTH: {
    INVALID_CREDENTIALS:        'AUTH.INVALID_CREDENTIALS',
    INVALID_REFRESH_TOKEN:      'AUTH.INVALID_REFRESH_TOKEN',
    ACCOUNT_LOCKED:             'AUTH.ACCOUNT_LOCKED',
    ACCOUNT_INACTIVE:           'AUTH.ACCOUNT_INACTIVE',
    ACCOUNT_PENDING:            'AUTH.ACCOUNT_PENDING',
    ACCOUNT_SUSPENDED:          'AUTH.ACCOUNT_SUSPENDED',
    ACCOUNT_TERMINATED:         'AUTH.ACCOUNT_TERMINATED',
    ACCOUNT_STATUS:             'AUTH.ACCOUNT_STATUS',
    PASSWORD_EXPIRED:           'AUTH.PASSWORD_EXPIRED',
    PASSWORD_TOO_SHORT:         'AUTH.PASSWORD_TOO_SHORT',
    PASSWORD_NEEDS_UPPERCASE:   'AUTH.PASSWORD_NEEDS_UPPERCASE',
    PASSWORD_NEEDS_LOWERCASE:   'AUTH.PASSWORD_NEEDS_LOWERCASE',
    PASSWORD_NEEDS_DIGIT:       'AUTH.PASSWORD_NEEDS_DIGIT',
    PASSWORD_NEEDS_SPECIAL:     'AUTH.PASSWORD_NEEDS_SPECIAL',
    CURRENT_PASSWORD_INCORRECT: 'AUTH.CURRENT_PASSWORD_INCORRECT',
    ACTIVATION_INVALID:         'AUTH.ACTIVATION_INVALID',
    RESET_INVALID:              'AUTH.RESET_INVALID',
    ACCESS_DENIED:              'AUTH.ACCESS_DENIED',
    TWO_FACTOR_REQUIRED:        'AUTH.TWO_FACTOR_REQUIRED',
    TWO_FACTOR_INVALID:         'AUTH.TWO_FACTOR_INVALID',
    TWO_FACTOR_EXPIRED:         'AUTH.TWO_FACTOR_EXPIRED',
    TWO_FACTOR_TOO_MANY_ATTEMPTS: 'AUTH.TWO_FACTOR_TOO_MANY_ATTEMPTS',
    USER_NOT_FOUND:             'AUTH.USER_NOT_FOUND',
  },

  // ── User CRUD & profile
  USER: {
    NOT_FOUND:           'USER.NOT_FOUND',
    EMAIL_EXISTS:        'USER.EMAIL_EXISTS',
    INVALID_ROLE:        'USER.INVALID_ROLE',
    INVALID_AGENCY:      'USER.INVALID_AGENCY',
    CANNOT_DELETE_SELF:  'USER.CANNOT_DELETE_SELF',
    CANNOT_MODIFY_SELF:  'USER.CANNOT_MODIFY_SELF',
    LAST_ADMIN:          'USER.LAST_ADMIN',
    PROFILE_LOCKED:      'USER.PROFILE_LOCKED',
    INVALID_STATUS:      'USER.INVALID_STATUS',
  },

  // ── Applicant lifecycle
  APPLICANT: {
    NOT_FOUND:        'APPLICANT.NOT_FOUND',
    ALREADY_EXISTS:   'APPLICANT.ALREADY_EXISTS',
    INVALID_TIER:     'APPLICANT.INVALID_TIER',
    INVALID_STATUS:   'APPLICANT.INVALID_STATUS',
    DRAFT_NOT_FOUND:  'APPLICANT.DRAFT_NOT_FOUND',
    PHOTO_INVALID:    'APPLICANT.PHOTO_INVALID',
    EMAIL_REQUIRED:   'APPLICANT.EMAIL_REQUIRED',
    NAME_REQUIRED:    'APPLICANT.NAME_REQUIRED',
    DELETE_REQUEST_PENDING: 'APPLICANT.DELETE_REQUEST_PENDING',
  },

  // ── Documents
  DOCUMENT: {
    NOT_FOUND:        'DOCUMENT.NOT_FOUND',
    TYPE_NOT_FOUND:   'DOCUMENT.TYPE_NOT_FOUND',
    INVALID_FILE:     'DOCUMENT.INVALID_FILE',
    FILE_TOO_LARGE:   'DOCUMENT.FILE_TOO_LARGE',
    UNSUPPORTED_TYPE: 'DOCUMENT.UNSUPPORTED_TYPE',
    EXPIRED:          'DOCUMENT.EXPIRED',
    ALREADY_VERIFIED: 'DOCUMENT.ALREADY_VERIFIED',
    REJECTION_REASON_REQUIRED: 'DOCUMENT.REJECTION_REASON_REQUIRED',
  },

  // ── Workflow + pipeline
  WORKFLOW: {
    NOT_FOUND:           'WORKFLOW.NOT_FOUND',
    STAGE_NOT_FOUND:     'WORKFLOW.STAGE_NOT_FOUND',
    STAGE_TEMPLATE_NOT_FOUND: 'WORKFLOW.STAGE_TEMPLATE_NOT_FOUND',
    STAGE_HAS_ASSIGNMENTS: 'WORKFLOW.STAGE_HAS_ASSIGNMENTS',
    INVALID_TRANSITION:  'WORKFLOW.INVALID_TRANSITION',
    ALREADY_AT_STAGE:    'WORKFLOW.ALREADY_AT_STAGE',
    ASSIGNMENT_NOT_FOUND: 'WORKFLOW.ASSIGNMENT_NOT_FOUND',
    ALREADY_ASSIGNED:    'WORKFLOW.ALREADY_ASSIGNED',
    APPROVAL_REQUIRED:   'WORKFLOW.APPROVAL_REQUIRED',
    REQUIREMENT_MISSING: 'WORKFLOW.REQUIREMENT_MISSING',
    NAME_REQUIRED:       'WORKFLOW.NAME_REQUIRED',
    DEFAULT_PROTECTED:   'WORKFLOW.DEFAULT_PROTECTED',
    PROGRESS_NOT_FOUND:  'WORKFLOW.PROGRESS_NOT_FOUND',
  },

  // ── Validation envelope (DTOs / class-validator). Phase 3.C will
  // expand this group with field-level codes.
  VALIDATION: {
    FAILED:                'VALIDATION.FAILED',
    INVALID:               'VALIDATION.INVALID',
    REQUIRED:              'VALIDATION.REQUIRED',
    EMAIL_INVALID:         'VALIDATION.EMAIL_INVALID',
    UUID_INVALID:          'VALIDATION.UUID_INVALID',
    URL_INVALID:           'VALIDATION.URL_INVALID',
    PHONE_INVALID:         'VALIDATION.PHONE_INVALID',
    PATTERN_INVALID:       'VALIDATION.PATTERN_INVALID',
    DATE_INVALID:          'VALIDATION.DATE_INVALID',
    STRING_EXPECTED:       'VALIDATION.STRING_EXPECTED',
    NUMBER_EXPECTED:       'VALIDATION.NUMBER_EXPECTED',
    BOOLEAN_EXPECTED:      'VALIDATION.BOOLEAN_EXPECTED',
    ARRAY_EXPECTED:        'VALIDATION.ARRAY_EXPECTED',
    OBJECT_EXPECTED:       'VALIDATION.OBJECT_EXPECTED',
    ALPHA_EXPECTED:        'VALIDATION.ALPHA_EXPECTED',
    ALPHANUMERIC_EXPECTED: 'VALIDATION.ALPHANUMERIC_EXPECTED',
    NUMBER_STRING_EXPECTED:'VALIDATION.NUMBER_STRING_EXPECTED',
    MIN_LENGTH:            'VALIDATION.MIN_LENGTH',
    MAX_LENGTH:            'VALIDATION.MAX_LENGTH',
    LENGTH:                'VALIDATION.LENGTH',
    MIN_VALUE:             'VALIDATION.MIN_VALUE',
    MAX_VALUE:             'VALIDATION.MAX_VALUE',
    OUT_OF_RANGE:          'VALIDATION.OUT_OF_RANGE',
    POSITIVE_REQUIRED:     'VALIDATION.POSITIVE_REQUIRED',
    NEGATIVE_REQUIRED:     'VALIDATION.NEGATIVE_REQUIRED',
    ENUM_INVALID:          'VALIDATION.ENUM_INVALID',
    NOT_IN_REQUIRED:       'VALIDATION.NOT_IN_REQUIRED',
    INVALID_FORMAT:        'VALIDATION.INVALID_FORMAT',
    PASSWORD_WEAK:         'VALIDATION.PASSWORD_WEAK',
    FILE_INVALID:          'VALIDATION.FILE_INVALID',
    FILE_TYPE_INVALID:     'VALIDATION.FILE_TYPE_INVALID',
    FILE_TOO_LARGE:        'VALIDATION.FILE_TOO_LARGE',
  },
} as const;

export type ErrorGroup = keyof typeof ErrorCodes;
export type ErrorCode = string;
